# Generated by Django 4.2.2 on 2023-08-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='about_me',
            field=models.TextField(max_length=128),
        ),
    ]
