# Generated by Django 4.2.2 on 2023-08-02 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='motivations', to=settings.AUTH_USER_MODEL),
        ),
    ]
