# Generated by Django 4.2.2 on 2023-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(max_length=512),
        ),
    ]
