# Generated by Django 4.2.2 on 2023-08-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_interest_users_alter_motivation_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='description',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='motivation',
            old_name='description',
            new_name='name',
        ),
    ]
