# Generated by Django 4.2.2 on 2023-08-02 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_rename_description_interest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='users',
        ),
        migrations.RemoveField(
            model_name='motivation',
            name='users',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.ManyToManyField(to='main_app.interest')),
                ('motivations', models.ManyToManyField(to='main_app.motivation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
