# Generated by Django 4.2.2 on 2023-08-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='type_tag',
            field=models.ManyToManyField(blank=True, to='main_app.typetag'),
        ),
    ]
