# Generated by Django 4.2.2 on 2023-08-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_typetag_post_type_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type_tag',
        ),
        migrations.AddField(
            model_name='post',
            name='type_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.typetag'),
        ),
    ]
