# Generated by Django 4.2.2 on 2023-08-12 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_postvote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostVote',
            new_name='PostKudos',
        ),
        migrations.CreateModel(
            name='ResponseKudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'response')},
            },
        ),
    ]
