# Generated by Django 4.2.2 on 2023-08-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_coderkaipoints_profileinfo_remove_motivation_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='users',
            new_name='user',
        ),
    ]
