# Generated by Django 4.2.2 on 2023-08-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_users_profileinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coderkaipoints',
            old_name='users',
            new_name='user',
        ),
    ]
