# Generated by Django 4.2.2 on 2023-08-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_users_coderkaipoints_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='motivations',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='interests',
            field=models.ManyToManyField(to='main_app.interest'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='motivations',
            field=models.ManyToManyField(to='main_app.motivation'),
        ),
    ]
