# Generated by Django 4.2.2 on 2023-08-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_kaigroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaigroup',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kaigroup',
            name='about',
            field=models.TextField(help_text='Short info about the group', max_length=252),
        ),
        migrations.AlterField(
            model_name='kaigroup',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
