# Generated by Django 4.2.2 on 2023-08-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_kaigroup_slug_alter_kaigroup_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
