# Generated by Django 4.2.2 on 2023-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_profileinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
