# Generated by Django 4.2.2 on 2023-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_profileinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default-avatar.png', null=True, upload_to='images'),
        ),
    ]
