# Generated by Django 4.2.2 on 2023-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_post_slug_alter_profileinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaigroup',
            name='group_image',
            field=models.ImageField(blank=True, default='images/default-avatar.png', null=True, upload_to='group_images'),
        ),
    ]
