# Generated by Django 4.2.2 on 2023-08-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_kaigroup_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='response_count',
            field=models.IntegerField(default=0),
        ),
    ]
