# Generated by Django 4.2.2 on 2023-08-25 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_post_response_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='response_count',
        ),
        migrations.AlterField(
            model_name='response',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='main_app.post'),
        ),
    ]
