# Generated by Django 4.2.2 on 2023-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_remove_post_response_count_alter_response_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coderkaipoints',
            new_name='kudos',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='coderkaipoints',
            new_name='kudos',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='kudos',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CoderKaiPoints',
        ),
    ]
