# Generated by Django 4.2.2 on 2023-08-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_alter_profileinfo_kudos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='rank',
            field=models.CharField(default='Code Cadet'),
        ),
    ]
