# Generated by Django 4.2.2 on 2023-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_profileinfo_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='interests',
            field=models.ManyToManyField(blank=True, to='main_app.interest'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='motivations',
            field=models.ManyToManyField(blank=True, to='main_app.motivation'),
        ),
    ]
